<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>ilyvion.LoadingProgress</RootNamespace>
        <AssemblyName>ilyvion.LoadingProgress</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <Publicize Include="Assembly-CSharp:Verse.LongEventHandler.StatusRectSize" />
        <Publicize Include="Assembly-CSharp:Verse.ModContentPack.ReloadContentInt" />
        <Publicize Include="Assembly-CSharp:Verse.ModContentPack.LoadPatches" />
        <Publicize Include="Assembly-CSharp:Verse.PlayDataLoader.DoPlayLoad" />
        <Publicize Include="Assembly-CSharp:Verse.LongEventHandler.eventQueue" />
        <Publicize Include="Assembly-CSharp:Verse.LongEventHandler+QueuedLongEvent" />
        <Publicize Include="Assembly-CSharp:Verse.LongEventHandler+QueuedLongEvent" />
        <Publicize Include="Assembly-CSharp:Verse.LongEventHandler.DrawLongEventWindowContents" />
        <Publicize Include="Assembly-CSharp:Verse.LongEventHandler.currentEvent" />
        <Publicize Include="Assembly-CSharp:Verse.LongEventHandler.UpdateCurrentEnumeratorEvent" />
        <Publicize Include="Assembly-CSharp:Verse.LongEventHandler.UpdateCurrentAsynchronousEvent" />
        <Publicize Include="Assembly-CSharp:Verse.LongEventHandler.UpdateCurrentSynchronousEvent" />
        <Publicize Include="Assembly-CSharp:Verse.LongEventHandler.eventThread" />
        <Publicize Include="Assembly-CSharp:Verse.LongEventHandler.ExecuteToExecuteWhenFinished" />
        <Publicize Include="Assembly-CSharp:Verse.LongEventHandler.executingToExecuteWhenFinished" />
        <Publicize Include="Assembly-CSharp:Verse.LongEventHandler.toExecuteWhenFinished" />
        <Publicize Include="Assembly-CSharp:Verse.Translator.PseudoTranslated" />
        <Publicize Include="Assembly-CSharp:Verse.ModContentPack.audioClips" />
        <Publicize Include="Assembly-CSharp:Verse.ModContentPack.textures" />
        <Publicize Include="Assembly-CSharp:Verse.ModContentPack.strings" />
        <Publicize Include="Assembly-CSharp:Verse.ModContentPack.assetBundles" />
        <Publicize Include="Assembly-CSharp:Verse.ModContentPack.allAssetNamesInBundleCached" />
        <Publicize Include="Assembly-CSharp:Verse.ModContentPack.allAssetNamesInBundleCachedTrie" />
        <Publicize Include="Assembly-CSharp:Verse.ModContentPack.patches" />
        <Publicize Include="Assembly-CSharp:Verse.ModAssetBundlesHandler.mod" />
        <Publicize Include="Assembly-CSharp:Verse.ModContentHolder`1.mod" />
        <Publicize Include="Assembly-CSharp:Verse.PatchOperationSequence.operations" />
        <Publicize Include="Assembly-CSharp:Verse.XmlInheritance.unresolvedNodes" />
        <Publicize Include="Assembly-CSharp:Verse.XmlInheritance.ResolveXmlNodes" />
        <Publicize Include="Assembly-CSharp:Verse.XmlInheritance+XmlInheritanceNode" />
        <Publicize Include="Assembly-CSharp:Verse.DirectXmlCrossRefLoader+WantedRef" />
        <Publicize Include="Assembly-CSharp:Verse.DirectXmlCrossRefLoader.wantedRefs" />
        <Publicize Include="Assembly-CSharp:Verse.PlayDataLoader.ResetStaticDataPre" />
        <Publicize Include="Assembly-CSharp:Verse.PlayDataLoader.ResetStaticDataPost" />
        <Publicize Include="Assembly-CSharp:Verse.LongEventHandler.levelLoadOp" />
        <Publicize Include="Assembly-CSharp:Verse.LongEventHandler.eventThread" />
        <Publicize Include="Assembly-CSharp:Verse.MapGenerator.tmpGenSteps" />
        <Publicize Include="Assembly-CSharp:Verse.MapDrawer.EnsureGlobalLayersInitialized" />
        <Publicize Include="Assembly-CSharp:Verse.MapDrawer.global" />
        <Publicize Include="Assembly-CSharp:Verse.MapDrawer.sections" />
        <Publicize Include="Assembly-CSharp:Verse.MapDrawer.SectionCount" />
        <Publicize Include="Assembly-CSharp:Verse.PostLoadIniter.saveablesToPostLoad" />
        <Publicize Include="Assembly-CSharp:Verse.Map.loadedFullThings" />
        <Publicize Include="Assembly-CSharp:Verse.QuickStarter.quickStarted" />
        <Publicize Include="0Harmony:HarmonyLib.MethodCreator" />
        <Publicize Include="0Harmony:HarmonyLib.MethodCreator..ctor" />
        <Publicize Include="0Harmony:HarmonyLib.MethodCreator.config" />
        <Publicize Include="0Harmony:HarmonyLib.MethodCreator.CreateReplacement" />
        <Publicize Include="0Harmony:HarmonyLib.MethodCreatorConfig" />
        <Publicize Include="0Harmony:HarmonyLib.MethodCreatorConfig.original" />
        <Publicize Include="0Harmony:HarmonyLib.MethodCreatorConfig.prefixes" />
        <Publicize Include="0Harmony:HarmonyLib.MethodCreatorConfig.postfixes" />
        <Publicize Include="0Harmony:HarmonyLib.MethodCreatorConfig.finalizers" />
        <Publicize Include="0Harmony:HarmonyLib.FaultBlockRewriter" />
        <Publicize Include="0Harmony:HarmonyLib.FaultBlockRewriter.Rewrite" />
    </ItemGroup>
</Project>
