name: Build

on:
  workflow_call:
    inputs:
      artifact-suffix:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      ProjectDependenciesBasePath: ..\..
      RimWorldSteamWorkshopFolderPath: ..\..\.deps\refs
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build Mod for 1.6
        env:
          RimWorldVersion: 1.6
        run: dotnet build --configuration Release LoadingProgress.sln

      - name: Upload Mod Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LoadingProgress-${{ inputs.artifact-suffix }}
          path: |
            About/
            Common/
            1.6/
            LICENSE
            README.md
            CHANGELOG.md
            LoadFolders.xml
            !**/.*
            !About/*.pdn
            !About/*.svg
            !About/*.ttf
